simple_app/config/routes.rb
Rails.application.routes.draw do

  root 'posts#index', as: 'home'

  get 'about' => 'pages#about', as: 'about'

  resources :posts

end

simple_app/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

simple_app/app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments
	validates :title, presence: true, length: { minimum: 5, maximum: 30 }
end

simple_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

simple_app/app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def about
		@title = "Pages Page"
	end
end

simple_app/app/controllers/posts_controller.rb
class PostsController < ApplicationController
	# this method will display all the values
	def index 
		@posts = Post.all
	end

	def show
		@post = Post.find(params[:id])
	end

	def new
		@post = Post.new
	end

	def create
		# render plain: params[:post].inspect
		@post = Post.new(post_params)
		if(@post.save)
			redirect_to @post
		else
			@message = "Post not saved"
			render 'new'
		end

		# redirect_to action: "show", params: @post
	end

	def edit
		@post = Post.find(params[:id])
	end

	def update
		@post = Post.find(params[:id])
		if(@post.update(post_params))
			redirect_to @post
		else
			@message = "Post not saved"
			render 'edit'
		end

	end

	def destroy
		@post = Post.find(params[:id])
		if(@post.destroy)
			redirect_to posts_path
		else
			@message = "Post not deleted"
			render 'show'
		end
	end
	
	private def post_params
		params.require(:post).permit(:title, :body)
	end


end

simple_app/app/helpers/application_helper.rb
module ApplicationHelper
end

simple_app/app/helpers/pages_helper.rb
module PagesHelper
end

simple_app/app/helpers/posts_helper.rb
module PostsHelper
end

simple_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<title>SimpleApp</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= stylesheet_link_tag    'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css' %>
	<%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js' %>

	<%= csrf_meta_tags %>
</head>
<body>
	<nav class="navbar navbar-light bg-light">
		<a href="#" class="navbar-brand">Blog App</a>
		<ul class="nav navbar-nav">
			<li class="nav-item"><%= link_to "Home", home_path %></li>
			<li class="nav-item"><%= link_to "About", about_path %></li>
			<li class="nav-item"><%= link_to "Create Post", new_post_path %></li>
			<li class="nav-item"></li>
		</ul>
	</nav>
	<div class="container">
		<%= yield %>
	</div>	

</body>
</html>

simple_app/app/views/pages/about.html.erb
<h1>About Page</h1>
<div>
	<span><%= @title %></span>
</div>

simple_app/app/views/posts/edit.html.erb
<style>
	.row h1, .row div {
		text-align: center;
	}
</style>
<div class="row">
	<h1> Edit Post</h1>
</div>
<div class="row">
	<div class="col-sm-12 col-md-6 col-md-offset-3">
		<%= form_for :post, url: post_path(@post), method: :patch do |f| %>
		<p>
			<%= f.label :title %>
			<%= f.text_field( :title, {:class => 'form-control', :placeholder => @post.title}) %>
		</p>
		<p>
			<%= f.label :body %>
			<%= f.text_field( :body, { :class => 'form-control', :placeholder => @post.body }) %>
		</p>
		<p>
			<%= f.submit({:class => 'btn btn-info'}) %>
		</p>
		<% end %>
	</div>
</div>

<div class="row">
	<% if @post.errors.any? %>
		<% @post.errors.full_messages.each do |msg| %>
			<div class="alert alert-danger"><%= msg %></div>
		<% end %>
	<% end %>
</div>
<div class="row">
<% if (@message) %>
	<div class="col-md-6 col-md-offset-3 btn-danger"> <%= @message %> </div>
<% end %>
</div>

simple_app/app/views/posts/index.html.erb
<div class="row" style="text-align: center;">
	<h3>All the posts</h3>
</div>
<div class="row">
	<% @posts.each do |post| %>
	<div class="col-sm-12 col-md-4" style="text-align: center;">
			<div class="well">
				<h5><%= post.title %></h5>
				<p>
					<%= post.body %>
				</p>
				<span><%= link_to "Read More", post_path(post), {:class => 'btn btn-info'} %></span>
			</div>
		</div>
	<% end %>
</div>

simple_app/app/views/posts/new.html.erb
<style>
	.row h1, .row div {
		text-align: center;
	}
</style>
<div class="row">
	<h1> Add Post</h1>
</div>
<div class="row">
	<div class="col-sm-12 col-md-6 col-md-offset-3">
		<%= form_for :post, url: posts_path do |f| %>
		<p>
			<%= f.label :title %>
			<%= f.text_field( :title, {:class => 'form-control' }) %>
		</p>
		<p>
			<%= f.label :body %>
			<%= f.text_field( :body, { :class => 'form-control' }) %>
		</p>
		<p>
			<%= f.submit %>
		</p>
		<% end %>
	</div>
</div>

simple_app/app/views/posts/show.html.erb
<div class="row">
	<div class="card">
		<div class="card-body">
			<div class="card-title"><%= @post.title %></div>
			<%= @post.body %>
		</div>
	</div>
</div>	
<div class="row">
	<div class="col-md-6">
		<%= link_to "Edit Post", edit_post_path(@post), { :class => 'btn btn-success' } %>	
	</div>
	<div class="col-md-6">
		<%= link_to "Delete Post", post_path(@post), 
			method: :delete, 
			:class => 'btn btn-danger' %>
	</div>
</div>
<div class="row">
	<% if @post.errors.any? %>
		<% @post.errors.full_messages.each do |msg| %>
			<div class="alert alert-danger"><%= msg %></div>
		<% end %>
	<% end %>
</div>
<div class="row">
<% if (@message) %>
	<div class="col-md-6 col-md-offset-3 btn-danger"> <%= @message %> </div>
<% end %>
</div>